### ISSUE TITLE
Fake Window Size

### ISSUE THREAD

**Issue by Simon0Harms** [saenzramiro/rambox#1055]
I can not find out how you can trigger this bug.
Yesterday I deleted the Ryver integration and created another one and it works.

Today i didn't get my other computer not to use the mobile mode.

I use Ubuntu 16.04 64 Bit.

Any Tipps?

**Comment by Simon0Harms** [comment]
I get an answer from the devs
"The only reason it should be loading in "mobile" mode is if the browser window is less than about 610 pixels either horizontally or vertically."

My Display is 1366*768
I have on top and one bottom bar and then the place  (Ubuntu Mate) and then the space which rambox need...

Is there a possibility to fake the window size?

**Comment by saenzramiro** [comment]
No, but I think the problem is that webviews inside Rambox starts with a size of around 600x400px and then are expanded to full size. This only happens the first time the webview is rendered, so if you reload the service by going to the River tab, right click and select "Reload" it should fix the problem.
