### ISSUE TITLE
Improvement: tab numbers

### ISSUE THREAD

**Issue by madisonhope** [saenzramiro/rambox#1227]
Hey everyone.  I'd see a lot of value in being able to show tab numbers for enabled tabs.  Given the nature of Rambox and inconsistent tab keybindings bindings, using hotkeys to switch tabs can be a guessing game as it currently stands.

**Comment by saenzramiro** [comment]
IMHO is not necessary to add the numbers, you can use Ctrl + Tab to navigate or Ctrl + NUMBER to go directly... like Google Chrome or any other browser.

**Comment by Trucido** [comment]
Vertical tabs would be amazing if possible, like a sidebar thing. It's tricky on Chrome/Chromium due to "reasons" but electron should allow it. It's been done before I'm sure, but to name one there's vscode and its sidebar thing. 
but at the moment there's much more important issues (like fixing URL copying and right click behavior and drag behavior), but this would be a good enhancement though especially once you start having way too many tabs.
