### ISSUE TITLE
Services incorrectly aligned.

### ISSUE THREAD

**Issue by 88scythe** [saenzramiro/rambox#1249]
My services are split into an "align: left" and an "align: right" category (work <=> private).
Added a new custom service (KIN calendar).
The two first items from the right-aligned servcies are now added at the end of the left-aligned services.
Tried drag-and-dropping services, but can't get them to be aligned right anymore.
https://imgur.com/a/otjC1

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 6.1.7601

**Comment by 88scythe** [comment]
Edited config for a service to "Align left", then saved, then changed back to "Align right", saved again, but no dice. Service stays stuck in the left row.

**Comment by dieresys** [comment]
I've experienced this issue and I've been investigating it. #1157 and #1127 are probably all related to this.

- The service bar reordering is handled by 'Ext.ux.TabReorderer'. 
- The service's tabs are aligned to either left or right by inserting a 'tbfill' spacer in the middle of the two groups.

TabReorderer doesn't seem to play well with the way services are aligned. When a left service is dragged to the right side, the 'tbfill' spacer gets aligned to the left, giving the false impression that the services alignments have been switched.
After this happens, any further reordering is futile, because what get's stored in the model is not represented in the screen. 

I will keep looking into it to try to find a solution, but I lack experience in Ext so it may take some time.

**Comment by dieresys** [comment]
This is what I meant:
I setup three services at the left: L, L2 and L3.
I setup two at the right: R and R2.
I change the background of the filler to red:
`document.getElementById("tbfill-1048").style.backgroundColor = "red";`

Before dragging L3 to the right:

![before-dragging-l3](https://user-images.githubusercontent.com/2255299/38887115-4e8aa7f0-424e-11e8-83b7-cf716006890d.png)

```
> Ext.getCmp("app-main-1010").items.items.forEach(function(item) {console.log(item.title || item.id)})
ramboxTab
L <-
L2 <-
L3 <-
tbfill
R->
R2 ->
```

When dragging L3 to the right, the R element is swapped to the left of the filler, however the code doesn't reflect the change:

![after-dragging-l3](https://user-images.githubusercontent.com/2255299/38887126-5b139176-424e-11e8-8d04-6d33767772e4.png)

```
> Ext.getCmp("app-main-1010").items.items.forEach(function(item) {console.log(item.title || item.id)})
ramboxTab
L <-
L2 <-
tbfill
R->
L3 <-
R2 ->
```

Furthermore, the `updatePositions` method in `MainController` doesn't update the `align` field on each service, leading to the corruption that @88scythe mentioned.

**Comment by dieresys** [comment]
PR #1603 won't solve the display issue (it seems an Ext problem), but the services properties will at least reflect the order in which the services are aligned.
