### ISSUE TITLE
Slack-Notifications

### ISSUE THREAD

**Issue by Feedy88** [saenzramiro/rambox#126]
I don't get any Slack notifications, only the sound when a new message comes in.

**Comment by itsjef** [comment]
I have the same issue. btw I think there should be tray notification too.

**Comment by saenzramiro** [comment]
Are you using v0.4.0?

**Comment by Feedy88** [comment]
Indeed using Version v0.4.0. Issue still maintains (Win 7)

**Comment by saenzramiro** [comment]
Ok, I will fix this.

**Comment by Feedy88** [comment]
Still not working for me. Need further system-insights?

**Comment by saenzramiro** [comment]
It will be fixed in next release (0.4.1).

**Comment by ccentofo** [comment]
I know this has been closed and fixed in 0.4.1. However, I am on 0.5.3 on Mac OS and I do not get any badges for slack. My Hangouts work and so does my Discord. A coworker of mine is getting slack badges and we have the same settings in slack and for Rambox, any thoughts about this? I only ever sporadically get banner notifications in the top right, but only sometimes.

**Comment by saenzramiro** [comment]
@ccentofo What about in latest version 0.5.9?

**Comment by ccentofo** [comment]
#926

**Comment by mminks** [comment]
+1

The problem still persists with 0.5.10 on Mac.

**Comment by nmat** [comment]
@mminks can you try this: 

There is a fix for notifications for slack: bc85177

This is not yet released thought but there is a workaround until the release that is in:
#1072

Please try the workaround to see if it works better for you. Also please upgrade to 0.5.10 to test it out there.

**Comment by mminks** [comment]
Thx @nmat
