### ISSUE TITLE
Include a flat white/dark tray icon

### ISSUE THREAD

**Issue by FerdinandoLM** [saenzramiro/rambox#1314]
It would be nice to use rambox with a consistent design. 

For example, if all my tray icons are white, it would be nice to have rambox to be white too, or dark for very light systems.

**Comment by Crouze** [comment]
I fully second that. Maybe it's nitpicking but Rambox is for now unusable for me because of its inconsistent linux tray icons (compared to all other all-white icons on the tray). The Rambox icons are also too large.

I'd like to see an option to use custom defined icons, for instance in the config json file.

As for now I'm stuck with Franz 4.0, where I at least can replace their tray icon with my own custom ones.

Thanks,
Marco

**Comment by Crouze** [comment]
Well at least I found on Linux how I can replace the systray icons with my own icons, so I'm all good and ditched Franz.

Should anyone be interested, they're in your Rambox installation folder (/opt/rambox in my case), in the resources sub folder, in the app.asar file. Extract the files, replace, and re-create app.asar with the asar tool.

Cheers,
Marco

**Comment by saenzramiro** [comment]
Yes, we will add this in a future release. There is another thread talking this, so I will close it.
