### ISSUE TITLE
Too much rambox instances on explorer. Uninstalling till an explanation.

### ISSUE THREAD

**Issue by parthi2929** [saenzramiro/rambox#1332]
Lately my Pc was struggling with about 90%  memory, and I see multiple Rambox instances occupying memory. Why so many instances? Its even more than the services I opened in Rambox. Suspicious so uninstalling it till an explanation from rambox.

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.15063

**Comment by pztrn** [comment]
Rambox launching at least one helper instance for every tab. Remember, it's still a browser.

**Comment by parthi2929** [comment]
I had only 4 tabs but instances were more, like 7 or something..

**Comment by Ash258** [comment]
It's how Electron works. Eash service run in custom process, which can also spawn new process (helper, render). On windows its extra because windows need Helper process for resource exchange and synchronization. So everytime you will have `Number of services + 1` processes. 

Sometimes even more if the service is "fat". Some pages are really huge and need more resources.

Better explanation [here](https://codeburst.io/deep-dive-into-electrons-main-and-renderer-processes-7a9599d5c9e2)
