### ISSUE TITLE
mysms doesn't stay login

### ISSUE THREAD

**Issue by oahon** [saenzramiro/rambox#173]
mysms logouts every time Rambox is closed. Also sets all settings to default state after login. 
## 

> Rambox 0.4.1
> Electron 1.3.1
> linux x64 4.6.4-1-ARCH

**Comment by dbtdsilva** [comment]
Any code injection that we might use to fix this?

**Comment by dbtdsilva** [comment]
Is it possible to inject some code on startup to fix it?

**Comment by saenzramiro** [comment]
You can inject custom JS code by going to Rambox tab and modify mysms service. In Advance Options section, write your custom JS code.

Please share the code if you fix it.

**Comment by dbtdsilva** [comment]
For some reason injection doesn't seems to be working. 
I wrote a simple console.log("hello\n"); and it didn't show off on console. I also tried the example from github but with a reduced cooldown and nothing seems to happen (even after the reload):
setInterval(function(){location.reload();}, 1000);
Although I'm able to manipulate it with Developer Tools.

**Comment by saenzramiro** [comment]
Did you reload Rambox after adding the custom JS code?

**Comment by dbtdsilva** [comment]
Yes I did.

I went to the Developers tools and it shows without any script inside the JS Inject Code:
`Uncaught TypeError: Cannot read property 'rows' of undefined` on VM80:1

I opened the file and it shows the following:
`function checkUnread(){var e=document.getElementsByClassName("unread"),t=0;for(i=0;i<e.length;i++)t+=parseInt(e[i].firstChild.innerHTML.trim());updateBadge(t)}function updateBadge(e){e>=1?document.title="("+e+") "+originalTitle:document.title=originalTitle}"https://app.mysms.com/#login"===document.baseURI&&(document.getElementsByClassName("innerPanel")[0].rows[0].style.display="none",document.getElementsByClassName("innerPanel")[0].rows[1].cells[0].firstElementChild.style.display="none",document.getElementsByClassName("msisdnLoginPanel")[0].style.display="inline");var originalTitle=document.title;setInterval(checkUnread,3000);`

Then I added a small JS code inside the "Inject Code" with an error on purpose.
`docxxx.getElementsByClassName("msisdnLoginPanel")[0]`
Error didn't show up at all on the Developers Tools.

Although it seems that it was concatenated to the script that is responsible for the unread messages which has the error. Basically the custom JS isn't being called because the script crashes with an error before it reaches my code.

**Comment by saenzramiro** [comment]
Probably that's the problem. I will take a look for next release.

**Comment by JonathanDaSilva** [comment]
Hi. I was able to "Fix" this just by creating a "_Custom Service".

You can't login with your google account, but appart from that everything seems fine, I have the counter of messages working. 

Hope this can't be usefull to other people and help debbuging too :)

**Comment by LaurentBerder** [comment]
I was having the same issue since the beginning.
@JonathanDaSilva I followed your advice, and it turned out I was even able to login with Google account.
