### ISSUE TITLE
Enable support for Pushbullet

### ISSUE THREAD

**Issue by scar45** [saenzramiro/rambox#185]
I didn't want to create this issue, as my plan was to use Pushbullet via a "_Custom Service", however after attempting to login, their site returns the following:
# Sorry, something went wrong.
- Local Storage seems to be unaccessible to us.
- Do you have cookies disabled?
- Some browser extensions can conflict with our site. Temporarily disable them to test this.

If you still can't log in, send us an email at hey@pushbullet.com.

---

I would love support for Pushbullet as I use it to send SMS (similar to MightyText), and since I have a paid plan, I would love to continue using it within Rambox. Bonus points if a tighter integration lead to badge notifications for unread SMS. I believe there is a [pretty well-documented API](https://docs.pushbullet.com/), so hopefully a hacky workaround by using a "_Custom Service" would not be needed.

Thanks much for Rambox -- it's a wonderful project!

---

Rambox Version: 0.4.1
Platform: linux (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0

**Comment by saenzramiro** [comment]
Ok, I will take a look.

**Comment by Stele77** [comment]
+1 - MUCH NEEDED!
Can use every Webservice i want, no probs. Just with Pushbullet i get an error!
As Rambox is just genius, and the way better App then "Franz", missing out Pushbullet seems like a real bad thing compared to such an otherwise exceptional software.. :)
When you can offer support for the most used services (Where Pushbullet is at the top for many users), you dont only offer a great help for possibly millions of users, but also put the icing on the cake of an outstanding App. 
Cant remember when an FOSS App gained so much deserved attention over such short time.. 
So i hope the best for your team and the project!
Steve

**Comment by scar45** [comment]
I just came across this other open source Pushbullet client. Wondering if you might be able to leverage some of its techniques, etc.. I haven't had time to delve into the details, but here's the link if you wanted to check it out: https://github.com/sidneys/pb-for-desktop

**Comment by scar45** [comment]
I was notified of the v0.4.4 and immediately downloaded it after reading the ChangeLog. Thanks VERY much for adding Pushbullet, it's working great!

**Comment by el3ctrician** [comment]
just updated to the lateset version and i got same error message for pushbullet, how can i send logs ?

**Comment by saenzramiro** [comment]
@el3ctrician I tested, and seems the messages comes back. I will check again this in next release.
