### ISSUE TITLE
[Feature Request] Local proxy support

### ISSUE THREAD

**Issue by krz37** [saenzramiro/rambox#203]
Hello, 
Will there be a support for local proxy like there is in browsers? I would like to be able to use services without having to disclose my IP address to them (since some of them like to know everywhere you go, not mentioning names here, it starts by f). This would allow people to redirect their use of these services to Tor.
Thank you in advance for considering this possibility :)

**Comment by saenzramiro** [comment]
Sure! I will consider this for next versions. :wink:

**Comment by remijouannet** [comment]
you can use "Chrome Command Line Switches" with
https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md
(on linux) /opt/Rambox/Rambox --proxy-server=address:port
you can add http://ipecho.net/ as a service on rambox to test if this is working

(i'm just sharing it here because i guess some people will search "proxy", in issues to check if anyone has a solution)

**Comment by krz37** [comment]
Tank you!  :dancer:
