### ISSUE TITLE
Remember last window size

### ISSUE THREAD

**Issue by biji** [saenzramiro/rambox#24]
When started, rambox will always maximized, instead remembering last window size before quit

thanks

**Comment by saenzramiro** [comment]
That's true, I will fix this for next release.

Thanks!

**Comment by Jimi-James** [comment]
I just upgraded to 4.0 from 3.0, which I imagine means I now have this commit in my copy of rambox, and now rambox will not remember that I had it maximized. I actually want it to start maximized and be maximized all the time, so it's very annoying suddenly having to manually maximize it every time it starts. Can't it also remember whether it was maximized, as most programs do? I'm use XFCE with xfwm4, so I can't really manually make it maximize on launch myself.

**Comment by saenzramiro** [comment]
Well, I couldn't test it in that OS.

I'm using [Electron Window State](https://github.com/mawie81/electron-window-state) library, and seems to be a bug from them. On Windows with Multi screen works great, remembers position, size, state (max/min). I will try to test it on XFCE.

**Comment by Jimi-James** [comment]
XFCE also knows how to remember whether a window was maximized, so my guess is something about the way you've set it to apply its last window size is overriding maximization, maybe because that step is happening *after* the window first spawns.

**Comment by saenzramiro** [comment]
Added in 0.4.0.

**Comment by Jimi-James** [comment]
It's still not remembering that it was maximized on my computers. Running 0.4.0.

**Comment by saenzramiro** [comment]
Interesting... I will take a look on this to find another solutions. Rambox is using [electron-window-state](https://github.com/mawie81/electron-window-state) plugin, so it's a bug for this plugin.

**Comment by Jimi-James** [comment]
OK, this is getting really weird. Just now, I compared 3 windows-state.json files: the one on my desktop, the one on my laptop, and the one on a backup of my desktop from when I KNOW it remembered being maximized. They were completely identical, including file permissions. However, my laptop won't remember and my desktop still remembered to start maxmimized. Then, I synced them with unison (as is routine) for the first time since before my last test/comment, overwriting my desktop's file with my laptop's, and now my desktop can't remember it was maximized, either.
