### ISSUE TITLE
Ignores autostart setting in Linux

### ISSUE THREAD

**Issue by Jimi-James** [saenzramiro/rambox#252]
### Steps to reproduce

1. Configure Rambox to not automatically start on system startup by unchecking that box in its preferences

### Expected behavior

Rambox does not automatically start on system startup

### Actual behavior

Rambox constantly recreates the ~/.config/autostart/Rambox.desktop file regardless of whether you've checked the box, which inherently makes it autostart on system startup

### ENVIRONMENT

> Rambox: v0.4.1

> OS: linux

> Arch: x64

**Comment by saenzramiro** [comment]
Related #232

**Comment by Jimi-James** [comment]
That's weird. I searched "is:issue autostart" before opening this issue and that one didn't show up in the results.

**Comment by saenzramiro** [comment]
No problem. :wink: 

I leave it open because your ticket is for Linux, but I know that is a bug for all OS.

**Comment by Pablohn26** [comment]
I have been researching about this issue and I think [here](https://github.com/saenzramiro/rambox/commit/91e2518065298c1b0605c168c6f0c0af7954772b) the disable option is not managed.  I found [nice information](https://github.com/loganfreeman/configuration/blob/e91e06b2981507f1d6bff4d3559a26ac356b1511/electron.md) that could help (I cannot build rambox due to a problem with the environment, but I hope it helps). 

It also fixs #232
