### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by eorroe** [saenzramiro/rambox#31]
- Switching Tabs (windows ctrl+tab, idk for other platforms :smile: )

**Comment by saenzramiro** [comment]
Sweet feature! :wink:

**Comment by jbbr** [comment]
`CTRL-+/-` for zoom would be nice too

**Comment by eorroe** [comment]
^ per origin

**Comment by eorroe** [comment]
Probably should leave this open so people can add more keyboard shortcuts if they have ideas? (I can't think of anymore that will come up but we never know)

**Comment by saenzramiro** [comment]
I prefer people create new issues for any other suggestions.

In next release, I added:

- Ctrl + Tab to navigate tabs forward.
- Ctrl + Shift + Tab to navigate tabs backward.
- Fixed @ shortcut, because was switching always to tab number 2.
- Added zoom to services with Ctrl + NumPlus, Ctrl + NumMinus and Ctrl +
NumZero.
