### ISSUE TITLE
Closing the window kills the entire application 

### ISSUE THREAD

**Issue by DerEnderKeks** [saenzramiro/rambox#369]
If I close the window, rambox completely quits. I would expect that if I close the window, rambox minimizes to tray. Also I can't double click the tray Icon.
## 

> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-38-generic

**Comment by simonwiles** [comment]
came to report the same issue; but while I'm here, a keyboard shortcut (Esc?) to "close" (i.e. minimize to tray) would be very welcome if it could be implemented at the same time.

**Comment by saenzramiro** [comment]
@simonwiles Sure, I will add that feature in a future release. #379

**Comment by pavanparasa** [comment]
The app is built very well, very robust, This will be my go to AIO messenger app from now on, the close to tray will make the experience much better, can't wait for this update :)

**Comment by chmercesmoreira** [comment]
Complementing what @DerEnderKeks said in the first message, when I receive a new message a notification pop up appears with the message and a button labeled "view", when I click on this button nothing happens when actually the app window should be open.

**Comment by didli** [comment]
> If I close the window, rambox completely quits.
Same here on Linux (Fedora 24 xfce)

**Comment by hiddenman** [comment]
Got the same problem.

**Comment by itsjef** [comment]
Isn't it fixed yet? 

> Linux Mint 18 Cinnamon

**Comment by saenzramiro** [comment]
No, it will be fixed in v0.5.0.

**Comment by weeman1337** [comment]
Just a note: #166 was a bug that it doesn't acutally quit when the window is closed.
This issue is the way around - so how should it do? ;)

Looks like we've two opinions what should happen when closing the window on linux:
- quit the app
- keep in tray

I suggest we should decide for a default behavior and add an option to Rambox so the other party is also happy that it can be configured.

**Comment by saenzramiro** [comment]
Yes, adding an option will be the best of course.

A good approach is to add a new option in the Preferences with a combobox, and options will be:

- Quit the app
- Keep it in tray
- Keep it in tray and Taskbar

**Comment by didli** [comment]
I totally agree. This is a quite common feature alongside some apps that can rest on panel trays. 
Le 25 nov. 2016 10:20 PM, Michael Weimann <notifications@github.com> a écrit :

**Comment by weeman1337** [comment]
@saenzramiro since I know the places where to look at, I'll send you a PR.

**Comment by weeman1337** [comment]
There are already optionsf or the task bar, but only for windows. I enabled them for all but mac for now. If it works on linux may depend on the linux system... Since there are already options for the task bar, I only added a field to control the "quit main window" behavior.

![screenshot from 2016-11-26 11-46-15](https://cloud.githubusercontent.com/assets/6216686/20639826/1a1ae274-b3ce-11e6-9658-4630693602e1.png)
