### ISSUE TITLE
Slack audio call broken as it opens in new browser window

### ISSUE THREAD

**Issue by svoop** [saenzramiro/rambox#400]
### Steps to reproduce (on Mac)
1. Make Firefox the default browser
2. In Rambox: select Slack
3. Start a one-to-one chat
4. Hit the little telephone icon to start a one-to-one audio call
### Expected behavior

The call should start either inside Rambox itself or in a new Chrome-window.
### Actual behavior

A new window is opened with the default browser Firefox. Since Firefox is lacking necessary bits, the call is not initiated:

```
Unfortunately, the calls feature is not available in this browser.
Please switch to Chrome.
```

☝️ This used to work up until 0.4.3. The Firefox window opened with the above error message, but the call started nonetheless right inside Rambox itself.
### ENVIRONMENT

Rambox: v0.4.4
OS: macOS Sierra

**Comment by kellywerks** [comment]
Same issue with Slack desktop.  Can call from window in browser but receive the same message when I try a call from the desktop app.

**Comment by edorivai** [comment]
Apologies in advance if this is not the right place to ask.

When starting a Slack call, the call opens in a modal which overlays the entire Slack interface. Am I missing something, or is there no way to open the call in an external window? It is very common for me to share snippets over the chat with people I'm in a call with, and this is impossible due to the modal overlay. Thanks!

**Comment by saenzramiro** [comment]
@edorivai In latest version, we removed the mask for the modal. So you can resize the window or move it to send files.
