### ISSUE TITLE
Login with .... (google)

### ISSUE THREAD

**Issue by gossi** [saenzramiro/rambox#428]
So, I added Asana (asana.com) as my custom service. I used google to login to asana, so there is a login button "Login with Google" which doesn't work.
### Steps to reproduce
1. Login to Asana once with google to create an account (on the website)
2. Add Asana as custom service
3. Press the button "Login with Google"
4. Nothing happens
### Expected behavior

A popup with the google authentication, provide credentials, login, use asana
### Actual behavior

There is a window opening and a tab in my default browser. The opened windows shows the google authentication page. The tab opened in my default browser waiting for the response from the opening window, which actually is opened from rambox. So the response is never returned to the tab which cannot return it to rambox and so no login is happening at all.
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: macOS Sierra
> 
> Arch: x64

Ref #378, #364

**Comment by saenzramiro** [comment]
The problem here is related with popups. I couldn't detect if the link is a normal link or a link for SSO. I couldn't create an scenario that shows popups inside Rambox for SSO and not opening a new browser tab. If the link is opened in a browser tab, the session will be lost so it will not work, but if is opened in a popup, yes.

The only idea that I have is to create some regex for URL and see if is a SSO for Google, Facebook, etc and force to open a popup manually.

When user clicks on a link, **new-window** event will fire up. See here:

https://github.com/saenzramiro/rambox/blob/master/app/ux/WebView.js#L235-L269

**Comment by gossi** [comment]
yes, I understand. As more services are having these kind of "login with ..." buttons. I guess it is a good idea to kinda "recognize" them to handle them properly... and if it is via regex.

**Comment by 88scythe** [comment]
+1 from me.
Rambox is now holding most of my communication and planning tools for both private and work. Only Asana is currently missing because of this bug.

**Comment by saenzramiro** [comment]
Yes, we have to find a way to fix this ASAP.

PR's are welcome.

**Comment by 88scythe** [comment]
@saenzramiro The issue is still there. Not sure why this issue was put on "closed"?

**Comment by nmat** [comment]
@88scythe when do you get it? because it works for me using gmail in 0.5.9

**Comment by 88scythe** [comment]
@nmat Original description of this bug is still valid for me.
- Add Asana as custom service in Rambox. (https://app.asana.com)
- Go to the Asana service in Rambox.
- Try to log in with a Google Account.
- When clicking the button, I briefly get a popup from Rambox, which promptly disappears, and then a new tab in my browser opens instead with the Google login page.
- If I try logging in there, it just remains loading (lost its connection with the Asana login session from within Rambox, probably ...)

**Comment by saenzramiro** [comment]
This is closed because it's related with another bug that we still have. It's not an easy bug to fix it, but we know it's an important bug.

**Comment by 88scythe** [comment]
Hi @saenzramiro Can you refer to the open bug number for this?
I've clicked around but am getting in circles, all bugs are referring to each other but are also all on closed?

**Comment by epixcz** [comment]
Yeah i just tried to add Tinder, that added web interface in last month and since it use 'Login with Facebook' button, it doesn't work. I'm little bit disappointed, that this is not fixed yet.

**Comment by devinturner** [comment]
Is there an update or link to an open issue? I am having the same issue using Google authentication for Flock. Thanks
