### ISSUE TITLE
Riot service should be able to use custom URL

### ISSUE THREAD

**Issue by pztrn** [saenzramiro/rambox#451]
Riot can be installed on own server, so users should be able to define custom URL in service's settings.

**Comment by scar45** [comment]
Would love to see this enhancement as well. Mainly for catching the badge change properly. Right now I am using the following code which isn't ideal as the badge count flashes constantly (probably due to the React framework of Riot:

`
function checkUnread() {
    var e = document.getElementsByClassName("mx_RoomTile_badge");
    var t = 0;
    for(i = 0; i < e.length; i++) {
        if (parseInt(e[i].textContent.trim()) % 1 === 0 ) {
            t += parseInt(e[i].textContent.trim());
        }
    }
    updateBadge(t);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 1000);
`
