### ISSUE TITLE
Add option to hide menu bar

### ISSUE THREAD

**Issue by nsrosenqvist** [saenzramiro/rambox#500]
On some Linux environments, such as GNOME-Shell, the menu bar looks really clunky and out of place. Please add an option to hide it like other Electron apps do (e.g. Atom). Would be greatly appreciated! Thanks!

**Comment by saenzramiro** [comment]
Can you share to me a screenshot of how looks Rambox with the menu? And Atom without menu?

**Comment by hughwilliams94** [comment]
This is a great idea!

**Comment by saenzramiro** [comment]
Did you check the "Auto-hide Menu bar" option in the Preferences?

**Comment by hughwilliams94** [comment]
I don' see this option in the preferences sorry. I am running Version 0.4.5 on Arch Linux with Electron 1.4.7

![screenshot_20170103_124738](https://cloud.githubusercontent.com/assets/15379654/21608227/24aff712-d1b3-11e6-9acd-ef937d3d1d62.png)

**Comment by saenzramiro** [comment]
Oh right, we hide that option in Linux because in popular distros you can't hide it.

But there is a way you can hide it. Be sure to have Rambox closed, so then you have to find the **~/.Rambox/config.json** file of Rambox, edit it and change the `hide_menu_bar` property to **true**. Open Rambox again.

**Comment by hughwilliams94** [comment]
Bingo, did just what I wanted! I seen this advise for other apps. Just in case anyone else needs to find the config.json mine was in the __~/.config/Rambox/__ directory.
