### ISSUE TITLE
Numerous notifications with Hangouts

### ISSUE THREAD

**Issue by mkenyon2** [saenzramiro/rambox#505]
I'm using both Rocket Chat and Hangouts. Notifications work well for Rocket Chat, but with Hangouts, if I get a message, I get multiple notifications.

I'm running Windows 10 with the latest updates.

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by pedropapa** [comment]
Confirmed on macOS Sierra

**Comment by TMartinPPC** [comment]
Also happening on Ubuntu 16.04 x64

**Comment by Jimi-James** [comment]
Yeah, really annoying. It just continuously flashes you a new notification every few seconds. The only way to "fix" it is to disable notifications in Hangouts, which also sadly disables the red number of unread messages on the tab (which also flashes every few seconds). It's been happening since either 4.4 or 4.5, but I don't think it's Rambox's fault. It seems more like Google changed the way desktop notifications are handled into this new annoying crap, and Rambox just needs to account for that in its code.

**Comment by billapepper** [comment]
This only happens for me in the following scenario:

On MacOS 10.11.6, if you leave Rambox running, and get a text message while away from your computer (screen is off due to idle), when you log back into your machine the unread count for Google Hangouts switches back and forth between the last received text message's area code, and the actual unread count, causing continual loop of notification dings until you "refresh" Google Hangouts tab... so, I'd suspect the count is being parsed somehow, and it's sometimes getting the last message's area code?

**Comment by pheijmans** [comment]
Also happens here.
very annoying

> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by fiunchinho** [comment]
This is happening to me

Version: 0.5.9
Platform: darwin (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by epixcz** [comment]
Yes, its pretty annoying. I'm considering switching to similar apps like Franz or Mangeyum. Definitely will check, if they have same problems.

**Comment by saenzramiro** [comment]
Is this happening in version 0.5.10?

**Comment by pedropapa** [comment]
@saenzramiro Yes it is. I don't know about Windows, but at least at macOS Sierra, when a hangouts message is received I receive the notification sound only one time, but the Rambox app icon jumps around on Dock until I open the unread conversation.

**Comment by Jimi-James** [comment]
@saenzramiro It's not still happening to me on Linux.

@pedropapa That sounds like "window flashing" (I don't know what it's really called but that's what Steam's settings call it), which is not the same thing as a desktop notification, and unlike a constantly flashing desktop notification, is a feature, not a bug. Without it, there'd be no easy way to tell you got a new message if the tray icon is deactivated and the window is minimized. Perhaps you should open a new issue as a feature request to provide the option to turn that off?

**Comment by ivanatpr** [comment]
[This page](https://github.com/saenzramiro/rambox/wiki/Inbox) should really warn you that signing out of hangouts in rambox will sign you out of hangouts in all other browsers as well.
