### ISSUE TITLE
Google Voice notifications

### ISSUE THREAD

**Issue by calexicoz** [saenzramiro/rambox#634]
Hi there,

There seems to be a similar issue with the new Google Voice, as there was with Hangouts.

### Steps to reproduce

1. Add custom service https://voice.google.com
2. Badge shows 300 notifications, despite none

### Expected behavior

The number of notifications pending is correct.

### Actual behavior

It's not.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: macOS 10.12.3

**Comment by saenzramiro** [comment]
Sorry but I don't have Voice so I cannot check the problem.

Can any of the community help with this?

**Comment by calexicoz** [comment]
It's actually gone for some reason. Closing. I'll re-open if it pops up again.

**Comment by cg505** [comment]
I'm having a similar issue. It's caused by the area code in phone numbers. If I navigate to my conversation with a 917 number, the page title is "Google Voice - (917) xxx-xxx". Rambox picks up the 917 in parentheses and thinks there are 917 notifications. Is there any way to disable the number of notifications badge?

**Comment by bawachhe** [comment]
I just came over here from Franz and the guy who made the Franz plugin for Google Voice made a PR for his plugin that might suggest the fix?
https://github.com/meetfranz/plugins/pull/169/files
