### ISSUE TITLE
What is the use of this?

### ISSUE THREAD

**Issue by SpEcHiDe** [saenzramiro/rambox#654]
Why would a person use this compared to the normal WhatsApp android application?

**Comment by MrChick** [comment]
Rambox isn't for replacing WhatsApp, it is for using WhatsApp Web (and hundreds other web-based tools) in a comfortable way.

So instead of having your browser open all the time to use WhatsApp Web, Facebook Messenger, ICQ, gmail, ..., ..., ... you use Rambox for those and your browser for actual browsing.

**Comment by SpEcHiDe** [comment]
What comfort will I gain by using your tool instead of web.whatsapp.com ? I will have to keep my mobile phone connected to the Internet 24*7, right ?

**Comment by MrChick** [comment]
Yes, you do, since that's how WhatsApp Web is working.

**Comment by SpEcHiDe** [comment]
തർക്കിക്കാൻ നമ്മൾ ഇല്ലേ
