### ISSUE TITLE
Left Click to Open Rambox from tray icon

### ISSUE THREAD

**Issue by GlebWork** [saenzramiro/rambox#748]
Launch app and minimize it to tray icon
Left click on icon does nothing (it should open client on click)

p.s. If this is correct behavior, that please consider that as Feature Request

-
> Ubuntu 16.04 with XFCE
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-67-generic

**Comment by tareko** [comment]
Same behaviour on:

Gnome Ubuntu 17.04 with gnome-shell

It makes rambox difficult to minimize

**Comment by tareko** [comment]
Not quite the exact same, but this issue seems related to https://github.com/saenzramiro/rambox/issues/700

**Comment by nmat** [comment]
https://github.com/saenzramiro/rambox/pull/728 might be a solution?

**Comment by tareko** [comment]
This does not fix the problem in my setup.

**Comment by nmat** [comment]
linux? because the test was really hard to do there because of third party lib. :/

**Comment by tareko** [comment]
Sorry, I don't understand your question. As above, I am using Gnome Ubuntu 17.04, which is linux

**Comment by nmat** [comment]
@tareko the reason I asked was because of below (electron docs):

Platform limitations:

On Linux the app indicator will be used if it is supported, otherwise GtkStatusIcon will be used instead.
On Linux distributions that only have app indicator support, you have to install libappindicator1 to make the tray icon work.
App indicator will only be shown when it has a context menu.
When app indicator is used on Linux, the click event is ignored.
On Linux in order for changes made to individual MenuItems to take effect, you have to call setContextMenu again.

However, the tray should work the same on all places IMO. But gonna look at what is wrong with my changes there. It worked better on windows because of focus etc. However if it fails on linux its not really a _fix_ :/

**Comment by tareko** [comment]
Aha. That explains a few things. However, GNOME uses GTK (aka Gnome Tool Kit), so it doesn't sound applicable.

**Comment by nmat** [comment]
if you want. You can see here: https://electron.atom.io/docs/api/tray/

:)

**Comment by saenzramiro** [comment]
Duplicate #608

**Comment by GlebWork** [comment]
@saenzramiro Thank you!
