### ISSUE TITLE
Login pop-up can't connect using embedded services (google, facebook..)

### ISSUE THREAD

**Issue by Mumrau** [saenzramiro/rambox#753]
### Steps to reproduce

Using on Linux Mint 18.1 Serena

### Expected behavior

Connect through gmail, or connect with any others authentication service (but I noticed the bug on Gmail cause this is the one I use under 2 windows install and it works well).

### Actual behavior

For both of the expected behaviors, there is when I trigger an action an infinite loading circle, and no behavioral changes happen. I then have to exit the app and reload it.

### ENVIRONMENT

Version: 0.5.3
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

[EDIT]I just tried signing up a new account with another mail and it works, I could log into that, it just looks that the web browser pop-up is not working.

**Comment by saenzramiro** [comment]
Yes, this is a problem we had from the beginning. I explained why we have this problem and why is so difficult to fix it [HERE](https://github.com/saenzramiro/rambox/issues/428#issuecomment-255727542).

Hopefully someone can help us with this... in the mean time I will close this issue because it's a common bug.

**Comment by spersico** [comment]
I also have the same problem.
