### ISSUE TITLE
Recover Slack team switch feature, available on site

### ISSUE THREAD

**Issue by soulchainer** [saenzramiro/rambox#761]
Slack has in their site menu an option for quicky switch between other teams you're registered. Can we have this in Rambox, please?

![2017-03-27-155859_1920x1080_scrot](https://cloud.githubusercontent.com/assets/169524/24362466/2bb2abf4-130d-11e7-9781-780d0c1fcfd4.png)

I mean, I understand that for people pretty active in some channels all the time is convenient to have direct access (I mean, in form of isolated tabs) to certain teams and get notified of changes in everyone of them all the time. But, if that's not your case, this is just... a memory hog.

I'm registered in a few slack teams, but I'm not pretty active **all the time** in all of it, not awaiting responses. So, the need of having a tab for every team I want to check from time to time is cumbersome.
For this kind of use it's better to have only one tab, for the Slack service, and being able to switch between teams, like Slack allows us in the web application. And... this service in Rambox is nothing more than a web application, right? I don't understand why this option is gone here. Because the meaning of using Rambox is to have all the communication centralized, and not having to depend on the usual browser for it.

### ENVIRONMENT

> Rambox: v0.5.3
> OS: Arch Linux
> Arch: x64

**Comment by saenzramiro** [comment]
The option to switch to other Slack Teams is because you already have a session created in those teams in your browser. For example, if you open an Incognito tab and sign in to one team, you will not see the switching option.

But I think there is a possibility to do this in Rambox following a few steps:

1. Once you have a Slack service running and logged in, go to Rambox tab and change the URL of that service to another team, then Save.
2. Rambox it will reload the Slack tab to the new URL automatically.
3. Sign in.
4. Repeat all steps to add other teams.

Works?

**Comment by soulchainer** [comment]
**It works!!**
Thank you very much, @saenzramiro 👍.
