### ISSUE TITLE
Wire can't be used on Rambox anymore - upgrade needed

### ISSUE THREAD

**Issue by MakisH** [saenzramiro/rambox#762]
Since today (28/3/2017), Wire doesn't load on Rambox 0.5.3 anymore.

### Steps to reproduce

1. Add Wire on Rambox
2. Try to use it.

### Expected behavior

Wire web interface loads and works normally on Rambox.

### Actual behavior

The message "This browser is not supported." is displayed, no functionality is available.

### ENVIRONMENT

> Rambox: v0.5.3

> Electron: 1.4.15

> OS: linux (Ubuntu 16.04)

> Arch: x64

> Chromium: 53.0.2785.143

> Node: 6.5.0

**Comment by wenbob** [comment]
wire homepage will check **navigator.userAgent** , I found I can't change it via inject code
```
navigator.userAgent = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
```

we need a **user agent** option.

**Comment by bennyn** [comment]
Hello, 

We are very pleased that [Wire](https://wire.com/) is used by the [Rambox](http://rambox.pro/) community. In our latest Wire release we raised up the browser versions which are required to run Wire in order to use the latest WebRTC API. Unfortunately this caused issues for users running LTS browser versions or third-party applications like Rambox. We therefore made adjustments to our code and pushed out a newer version which should bring back Rambox support.

Can you verify that?

Best from Berlin,
Benny — *Web Developer at Wire*

**Comment by fungs** [comment]
I just checked and it does not seem to work here... This is rambox 0.5.3 on Linux 64 bit

**Comment by bennyn** [comment]
Thanks for the reply, @fungs. We are on it: https://github.com/wireapp/wire-webapp/issues/949

**Comment by edmundlaugasson** [comment]
Confirm that on rambox 0.5.3, 64-bit, Linux does not work. Tested in similar app (unfortunately not free and open-source) [Franz](http://meetfranz.com/) and there it worked.

**Comment by ruiumbelino** [comment]
@bennyn, still doesn't work.

Thanks

**Comment by fungs** [comment]
Just to summarize: rambox needs an update because it sets the chromium version and user agent for wire to a fake string which is below the required wire minimum version (although the actual version is sufficient). See pull request #792 

Rambox users are waiting for the fix to be merged and rolled out. Thanks!

**Comment by saenzramiro** [comment]
Ok, I will take a look on this.

**Comment by saenzramiro** [comment]
This will be fixed in next release thanks to @lipis in #792. For now, you can use Wire as a Custom Service.

**Comment by fungs** [comment]
Apart from the fix which is not contained in a major release version, Wire started working again, probably due to changes or a workaround by the provider. Thanks!

**Comment by saenzramiro** [comment]
:clap:
