### ISSUE TITLE
Flatpak installation

### ISSUE THREAD

**Issue by aparcar** [saenzramiro/rambox#860]
As rambox get frequent updates it would be handy to provide a simple [flatpak](flatpak.org) installtion.

**Comment by aiphee** [comment]
Agree, snap would also be to consider.

**Comment by nmat** [comment]
@aiphee Please see: https://github.com/saenzramiro/rambox/pull/824

**Comment by saenzramiro** [comment]
Probably we will use Snap in the future.

**Comment by Mikaela** [comment]
Could this issue be reopened? Snap is not Flatpak, so I don't think request for Flatpak is fixed by saying to support Snap. They also aren't mutually exclusive as far as I know of.

I have also understood snap to be centralized (not supporting third party (not-Canonical Ltd.) repositories at all) in addition to being very Ubuntu-centric and less widely supported than Flatpak. 

* [Adoption of Flatpak vs Snap](https://kamikazow.wordpress.com/2017/02/09/adoption-of-flatpak-vs-snap/) seems to be the simplest overview except that I have no idea how up-to-date it is on how widely either is supported. As Arch user I can only say that snap is not in community repo, it's in the AUR which I personally would like to keep as lower priority than Flatpak which is in Arch extra repository.
    * [Notification on snapd being removed from Arch repositories.](https://forum.snapcraft.io/t/updates-to-snapd-package-on-arch/1467/41)

**Comment by Ash258** [comment]
Its much effort for almost nothing in this state. Flatpak buiilding is difficult in many ways and need to be tested on lots of distributions, dependencies. And now there are more relevant issues than this.
On linux platform are almost every type of installers available.
When deploying of snap will be done it will be much smoother for basic user. (Better than downloading file, unpacking it and run some command, etc.)
So as said in https://github.com/saenzramiro/rambox/issues/860#issuecomment-306835940 .
This issue could be re-open for someone, who know background of flatpak installer and could help with it. But that does not depend on me 🙂
