### ISSUE TITLE
Hangouts is crashing!

### ISSUE THREAD

**Issue by evandroalb** [saenzramiro/rambox#871]
Hangouts account is crashing on the screen, rambox process starts to consume 4gb of ram and CPU goes to 100%. https://i.imgur.com/W67xue4.png

I've tried to clear cache, uninstall and install again... Same problem.

	
	-
	> Rambox 0.5.8
	> Electron 1.7.1
	> win32 x64 10.0.15063

**Comment by JamesValero** [comment]
This is the same issue as #868

**Comment by kuteninja** [comment]
Here's some more info about the crashes, it seems that one window is able to load if you managed to login, the other is showing me the login, but I can't click on anything it's loading eternally probably due to that same player.js error

![hangouts captura](https://cloud.githubusercontent.com/assets/438623/26317873/578fb9fc-3eef-11e7-868f-9bb2794c5207.jpg)

**Comment by nmat** [comment]
Can you please test this using version 0.5.9?

**Comment by kuteninja** [comment]
> Can you please test this using version 0.5.9?

Seems to be fixed on v0.5.9 both Windows and macOS Sierra :D
