### ISSUE TITLE
Error after adding Whatsapp

### ISSUE THREAD

**Issue by MitteMedia** [saenzramiro/rambox#906]
Im getting an Java Script Error with any Whatsapp Action (Uncaught Exception).
I added Whatsapp after todays update:
https://drive.google.com/file/d/0Bxgs2DcL7bZUcEQ4QnFPazdFNmc/view?usp=sharing

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 6.1.7601

**Comment by saenzramiro** [comment]
Do you still have this problem with latest version?

**Comment by ZORG-Industries** [comment]
No at the Moment its running well but it seems to have sometimes Problems
with loading the newsfeed in linkedin. Can be me since im using it behind a
proxy but usually it runs smooth but Yesterday i had to lockout and then
restart Rambox to load the feed again.

If you have feature time:
- please add: Xing (its the german linkedin).
- make a smartphone version of Rambox there are no good multimessengers...

Thanks for your Work!
If you need help with german translations feel free to get in touch with me
:)

Cheers
Dirk

Am 15.07.2017 01:15 schrieb "Ramiro Saenz" <notifications@github.com>:
